name: New Event
description: Submit a new developer event in devrelops.club calendar
title: "[New event]: 请输入活动名称"
labels: ["event"]
assignees:
  - shinyzhu
body:
  - type: markdown
    attributes:
      value: |
        感谢分享开发者活动到DevRelOps Club日历。请填写下列信息，Issue会由维护者转换成yml数据文件，然后所有订阅者就可以看到了。
  - type: input
    id: event-date
    attributes:
      label: 活动举办日期
      description: 请按照“年-月-日“（yyyy-MM-dd）的格式输入活动举办的开始日期。
      placeholder: 2022-10-24
    validations:
      required: true
  - type: input
    id: event-date-end
    attributes:
      label: 活动举办结束日期
      description: 请按照“年-月-日“（yyyy-MM-dd）的格式输入活动举办的结束日期。
      placeholder: 2022-10-25
    validations:
      required: true
  - type: textarea
    id: event-description
    attributes:
      label: 活动简介
      description: 请输入活动介绍、讲师信息等
      placeholder: 
      value: 
    validations:
      required: true
  - type: dropdown
    id: event-categories
    attributes:
      label: 活动类型
      description: 请从列表里选择活动的类型
      options:
        - 线上活动（默认）
        - 线下活动
        - 黑客松比赛
        - 技术大会
        - 内部培训
    validations:
      required: true
  - type: input
    id: event-location
    attributes:
      label: 活动举办地点
      description: 请输入活动举办的地点，在线活动输入“在线”即可。
      placeholder: 上海市浦东嘉里酒店
    validations:
      required: true
  - type: input
    id: event-url
    attributes:
      label: 活动网站
      description: 请输入活动的具体网址。
      placeholder: https://devrelops.club
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://devrelops.club/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true